motordriver_node:
  ros__parameters:
    simulation: False

odom_node:
  ros__parameters:
    wheel_radius: 0.2
    wheel_base: 0.6
    ticks_per_revolution: 1000
    
cmd_vel_node:
  ros__parameters:
    wheel_radius: 0.3
    wheel_base: 0.7